#!/bin/bash
echo "$(cat -n pattern.sh)"
echo "case sensitive:$(grep abc pattern.sh)"
echo "in case-sensitive:$(grep -i abc pattern.sh)"
echo "perticular word:$(grep -w abc pattern.sh)"
echo "with in case-insensitive:$(grep -w -i abc pattern.sh)"
echo "word which should be in line: $(grep -x -i abc pattern.sh)"
echo "before word lines:$(grep RED color.sh -B 1)"
echo "after word lines: $(grep RED color.sh -A 1)"
echo "line word character:$(wc color.sh)"
echo "sorting:$(cat pattern.sh |sort -n)"
echo "sort with remove duplicates:$(cat pattern.sh | sort -n |uniq)"
echo "sort with duplicates:$(cat pattern.sh | sort -n |uniq -d)"
echo " start with:$(grep ^a pattern.sh)"
echo "ending with:$(grep c$ pattern.sh)"
echo "remove empty lines:$(cat pattern.sh |grep -v '^$')"
