#!/bin/bash
echo -e "hi\nhello"
echo -e "good\tmorning"
echo -e "\e[31m foreground-color RED"
echo -e "\e[32m foreground-color GREEN"
echo -e "\e[33m foreground-color YELLOW"
echo -e "\e[34m foreground-color BLUE"
echo -e "\e[35m foreground-color MAGENTA"
echo -e "\e[36m foreground-color CYAN"
echo -e "\e[37m foreground-color WHITE"
echo -e "\e[41m foreground-color RED"
echo -e "\e[42m background-color GREEN"
echo -e "\e[43m background-color YELLOW"
echo -e "\e[44m background-color BLUE"
echo -e "\e[45m background-color MAGENTA"
echo -e "\e[46m background-color CYAN"
echo -e "\e[47m background-color WHITE"
echo -e "\e[00m back to normal color"
echo -e "\e[1;33;41m Enable Color \e[0m"
echo " mail -s HELLO root@ip-172-31-89-138"
echo -n "hello"
echo " helllo world"
echo "$(ls -l *.sh)"
