#!/bin/bash
echo "column field: $(echo -e "a\tb\tc")"
echo "perticular column: $(echo -e "a\tb\tc" |cut -f1)"
echo "display column 1 and 3:$(echo -e "a\tb\tc" |cut -f1,3)"
echo "display cols 1 2 3:$(echo -e "a\tb\tc" |cut -f1-3)"
echo "cut with : line: $(cat pen.sh |cut -f 1 -d :)"
echo "character display: $(echo rajashreer |cut -c 1-3)"
echo "conver col to row: $(echo -e "1\n2\n3" |xargs)"
echo "rows to cols: $(echo -e "1\t2\t3" |xargs |xargs -n1)"
echo "avoid space: $(echo -e "a\tb\t\tc\td" | awk '{print $2}')"
echo "print word: $(awk '/RED/ {print }' color.sh)"
echo "both same grep: $(grep RED color.sh)"
echo "display all colum : $(awk -F : '{print $1,$NF}' color.sh)"
echo " disp:$(awk -F : '/GREEN/{print $1}' color.sh)"
