#!/bin/bash
echo " print file: $(sed -e '/raj/ p' emp.txt)"
echo " print wiyhout output: $(sed -i -e '/raj/ p' emp.txt)"
echo "disp line word to word which to specify: $(sed -n -e '/raj/,/sonu/ p' emp.txt)"
echo "disp 2nd  line : $(sed -n  '2 p' emp.txt)"
echo " disp 3rd to last: $(sed -n  '3,$ p' emp.txt)"
echo "disply odd line: $(sed -n '1~2 p' emp.txt)"
echo "display even line: $(sed -n '2~2 p' emp.txt)"
echo " display word to specify with line num: $(sed -n  '/sonu/,2 p' emp.txt)"
echo "display cmd in file: $(sed -n -f t.sed emp.txt)"
echo "delete 4th line: $(sed  '4 d' emp.txt)"
echo "delete word with line: $(sed '/raj/ d' emp.txt)"
echo "delete emptyline it changes in file only: $(sed -i -e '/^$/ d' emp.txt)"
echo "substitute all  word which is relate to another: $(sed 's/MNC/Manager/' emp.txt)"
echo "replace perticular word with replace other thing: $(sed '/laxmi/s/MNC/Manager/' emp.txt)"
echo "replace line number with other:$(sed -e '3 s/shiva/SHIVA/' emp.txt)"
echo " replace only first:$(echo apple ant | sed 's/a/A/')"
echo "replace global : $(echo apple ant | sed 's/a/A/g')"
echo "replace 2nd: $(echo apple ant | sed 's/a/A/2')"
echo "case sensitive not change: $(echo raj | sed 's/Raj/shree/')"
echo "case in sensitive will chnage: $(echo raj | sed 's/Raj/Raji/i')"
